title: Darcy Joseph # your name (or website title) here
logo: "/images/darcyCircle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br/>5th Year Undergraduate<br/>
  University of Adelaide
  <br/>
  B.Eng - Electrical & Electronic
  <br/>
  BMaCompSci - Computer Science
  <br/><br/>
  <a href="https://www.linkedin.com/in/darcy-joseph-5293031a5/">LinkedIn</a> 
  
github:
  is_project_page: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
